### ISSUE TITLE
Telemetry: use correct version for opentelemetry-exporter-prometheus

### ISSUE THREAD

**Issue by Allob** [epam/ai-dial-sdk#107]
Trying to add aidial-sdk[telemetry] to the dependency leads to the warning:
```
Warning: The file chosen for install of opentelemetry-exporter-prometheus 1.12.0rc1 (opentelemetry_exporter_prometheus-1.12.0rc1-py3-none-any.whl) is yanked. Reason for being yanked: Version is deprecated.
```
See https://pypi.org/project/opentelemetry-exporter-prometheus/#history

Non-deprecated version of opentelemetry-exporter-prometheus should be used. Most likely, the 0.41b0 - same as for other instrumentations.

**Comment by adubovik** [comment]
It was fixed in https://github.com/epam/ai-dial-sdk/pull/103
